version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/initdb.sql
    
  fastapi-service:
    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    


